services:
    rbm.ed2k.listener:
        class: rbm\ed2k\event\main_listener
        arguments:
            - '@language'
            - '@request'
            - '%core.root_path%'
        tags:
            - { name: event.listener }
