services:
    rbm.ed2k.listener:
        class: rbm\ed2k\event\main_listener
        arguments:
            - '@template'
            - '@user'
            - '@request'
            - '%core.root_path%'
        tags:
            - { name: event.listener }
